config/routes.rb
Rails.application.routes.draw do
  resources :surveys
  resources :components, only: [:create, :destroy]
  root "surveys#new"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/component.rb
class Component < ApplicationRecord
  belongs_to :survey
end

app/models/survey.rb
class Survey < ApplicationRecord
	validates :name, presence: true 
	has_many :components, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	skip_before_action :verify_authenticity_token

end

app/controllers/components_controller.rb
class ComponentsController < ApplicationController
  def create
    @component = Component.new(component_params)
    if @component.save
      render json: @component, status: :created
    else
      render json: @component.errors, status: :unprocessable_entity
    end
  end

  def update
    @component = Component.find(params[:id])
    if @component.update(component_params)
      head :no_content
    else
      render json: @component.errors, status: :unprocessable_entity
    end
  end

  def destroy
    @component = Component.find(params[:id])
    @component.destroy
    head :no_content
  end

  private

  def component_params
    params.require(:component).permit(:component_type, :content, :position_x, :position_y, :survey_id)
  end
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  before_action :set_survey, only: %i[edit update destroy show]

  def index
    @surveys = Survey.paginate(page: params[:page], per_page: 5)
    respond_to do |format|
      format.html
      format.json { render json: @surveys }
    end
  end

  def new
    @survey = Survey.new
  end

  def create
    @survey = Survey.new(survey_params)
    respond_to do |format|
      if @survey.save
        format.html { redirect_to edit_survey_path(@survey) }
        format.json { render json: @survey, status: :created }
      else
        format.html { render :new }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    # @survey = Survey.find(params[:id])
  end

  def update
    respond_to do |format|
      if @survey.update(survey_params)
        format.html { redirect_to @survey }
        format.json { render json: @survey }
      else
        format.html { render :edit }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    respond_to do |format|
      format.html
      format.json { render json: @survey }
    end
  end

  def destroy
    @survey.destroy
    respond_to do |format|
      format.html { redirect_to surveys_path, notice: 'Survey was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private

  def set_survey
    @survey = Survey.find(params[:id])
  end

  def survey_params
    params.require(:survey).permit(:name, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/components_helper.rb
module ComponentsHelper
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EasySurveyApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.13.3/jquery-ui.min.js" integrity="sha512-Ww1y9OuQ2kehgVWSD/3nhgfrb424O3802QYP/A5gPXoM4+rRjiKrjHdGxQKrMGQykmsJ/86oGdHszfcVgUr4hA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/surveys/edit.html.erb
  <title>Easy Survey</title>
  <style>
    #survey-container {
      width: 900px;
      height: 1273px;
      border: 1px solid #ccc;
      position: relative;
    }
    .component {
      position: absolute;
    }
  </style>
</head>
<body>
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <h3>Toolbox</h3>
      <button id="add-label" class="btn btn-secondary">Add Label</button>
      <button id="add-input" class="btn btn-secondary">Add Input</button>
    </div>
    <div class="col-md-9">
      <div id="survey-container">
        <% @survey.components.each do |component| %>
          <div class="component" data-id="<%= component.id %>" style="width: 900px; height: 1273px; border: 1px solid #ccc;">
            <% if component.component_type == "label" %>
              <span contenteditable="true"><%= component.content %></span>
            <% else %>
              <input type="text" value="<%= component.content %>">
            <% end %>
            <button class="delete-component btn btn-danger btn-sm">Delete</button>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>


<script>
  $(document).ready(function() {
    var surveyId = <%= @survey.id %>; // Assuming @survey.id contains the survey ID
    var csrfToken = $('meta[name="csrf-token"]').attr('content');

    function setCsrfToken(xhr) {
      xhr.setRequestHeader('X-CSRF-Token', csrfToken);
    }
       

    function makeDraggable(component) {
      component.draggable({
        containment: "#survey-container",
        stop: function(event, ui) {
          var componentId = $(this).data("id");
          var position = ui.position;
          $.ajax({
            url: `/components/${componentId}`,
            type: 'PATCH',
            data: { component: { position_x: position.left, position_y: position.top } },
            beforeSend: setCsrfToken
          });
        }
      });
    }

    $(".component").each(function() {
      makeDraggable($(this));
    });

    $("#add-label").click(function() {
      var newLabel = $('<div class="component"><span contenteditable="true">New Label</span><button class="delete-component btn btn-danger btn-sm">Delete</button></div>');
      $("#survey-container").append(newLabel);
      makeDraggable(newLabel);
      saveNewComponent(newLabel, "label");
    });

    $("#add-input").click(function() {
      var newInput = $('<div class="component"><input type="text" value="New Input"><button class="delete-component btn btn-danger btn-sm">Delete</button></div>');
      $("#survey-container").append(newInput);
      makeDraggable(newInput);
      saveNewComponent(newInput, "input");
    });

    function saveNewComponent(component, type) {
      $.ajax({
        url: '/components',
        type: 'POST',
        data: { component: { component_type: type, content: '', survey_id: surveyId } },
        beforeSend: setCsrfToken,
        success: function(data) {
          component.attr('data-id', data.id);
        }
      });
    }

    $(document).on("click", ".delete-component", function() {
      var component = $(this).closest(".component");
      var componentId = component.data("id");
      $.ajax({
        url: `/components/${componentId}`,
        type: 'DELETE',
        beforeSend: setCsrfToken,
        success: function() {
          component.remove();
        }
      });
    });
  });
</script>

app/views/surveys/index.html.erb
<div class="container">
  <h1 class="my-4">Surveys</h1>
  <ol class="list-group ">
    <% @surveys.each do |survey| %>
      <li class="list-group-item">
      	<%= survey.id %>.
        <%= survey.name %>
        <%= link_to 'Edit', edit_survey_path(survey), class: 'btn btn-primary btn-sm ml-2' %>
        <%= link_to 'show', survey_path(survey), class: 'btn btn-info btn-sm ml-2' %>
        <%= link_to 'Delete', survey_path(survey), data: { "turbo-method": :delete }, class: 'btn btn-danger btn-sm ml-2' %>
      </li>
    <% end %>
  </ol>
  <ul class="pagination">
    <%= will_paginate @surveys, class: 'page-item' %>
  </ul>
</div>

app/views/surveys/new.html.erb
<%= form_with model: @survey, url: surveys_path do |form| %>
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control", required: true %>
  </div>
  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class: "form-control" %>
  </div>
  <%= form.submit "Create Survey", class: "btn btn-primary" %>
<% end %>

app/views/surveys/show.html.erb
<div class="container">
  <p><strong>Name:</strong> <%= @survey.name %></p>
  <p><strong>Description:</strong> <%= @survey.description %></p>
</div>